# Generated by Django 5.0 on 2024-08-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_layouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='message',
        ),
    ]
