# Generated by Django 5.0 on 2024-09-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volonteers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
